# Generated by Django 3.2.8 on 2023-10-24 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('image', models.ImageField(null=True, upload_to='imagenes/')),
                ('descripcion', models.TextField(null=True)),
            ],
        ),
    ]
